---
Name: sharethis
Before:
  - '#app'
After:
  - '#coreconfig'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SunnysideUp\ShareThis\ShareThisSiteConfigDE

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SunnysideUp\ShareThis\ShareThisSTE
    - SunnysideUp\ShareThis\SocialNetworksSTE
---
Only:
  classexists: Sunnysideup\DataobjectSorter\DataObjectSorterDOD
---
SunnysideUp\ShareThis\ShareThisDataObject:
  extensions:
    - Sunnysideup\DataobjectSorter\DataObjectSorterDOD

SunnysideUp\ShareThis\SocialNetworkingLinksDataObject:
  extensions:
    - Sunnysideup\DataobjectSorter\DataObjectSorterDOD
